Repository 2jae6/LiarGame, pull requests merged in 2022-05, with the labels that each got.

#17 라이어게임 퓨처 로직 개발
  LiarGame/Sources/Model/LiarGameModel.swift
  LiarGame/Sources/Reactor/LiarGameReactor.swift
  LiarGame/Sources/ViewController/HomeViewController.swift
  LiarGame/Sources/ViewController/LiarGame/LiarGameModeViewController.swift
  LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
  LiarGame/Sources/ViewController/LiarGame/LiarGameViewController.swift
  LiarGame/Sources/ViewController/SplashViewController.swift
Labels: 🚀 feature 🚀

#16 RandomMusicQuiz 무한로딩, 업데이트 오류 수정
  LiarGame/Sources/Reactor/RandomMusicQuizReactor.swift
  LiarGame/Sources/Repository/RandomMusicRepository.swift
  LiarGame/Sources/ViewController/RandomMusicQuiz/RandomMusicQuizViewController.swift
Labels: 🐛 Bug 🐛, 🦴 Refactoring 🦴

#19 fix: 프로젝트 생성 시 asset import 문제 수정
  LiarGame/Resources/Assets.xcassets/launch.dataset/Contents.json
  LiarGame/Resources/Assets.xcassets/launch_bottom.imageset/Contents.json
  LiarGame/Resources/Assets.xcassets/launch_title.imageset/Contents.json
  LiarGame/Sources/ViewController/SplashViewController.swift
Labels: 🐛 Bug 🐛, 🚨 Emergency 🚨

#20 SwiftLint SwiftFormat 추가
  .swiftformat
  LiarGame/Application/AppDelegate.swift
  LiarGame/Sources/Model/LiarGameModel.swift
  LiarGame/Sources/Model/Music.swift
  LiarGame/Sources/Reactor/HomeReactor.swift
  LiarGame/Sources/Reactor/LiarGameModeReactor.swift
  LiarGame/Sources/Reactor/LiarGameReactor.swift
  LiarGame/Sources/Reactor/LiarGameSubjectReactor.swift
  LiarGame/Sources/Reactor/RandomMusicQuizReactor.swift
  LiarGame/Sources/Repository/RandomMusicRepository.swift
  LiarGame/Sources/Utils/YTPlayerViewDelegateProxy.swift
  LiarGame/Sources/ViewController/HomeViewController.swift
  LiarGame/Sources/ViewController/LiarGame/LiarGameModeViewController.swift
  LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
  LiarGame/Sources/ViewController/LiarGame/LiarGameViewController.swift
  LiarGame/Sources/ViewController/RandomMusicQuiz/DashedLineBorderdLabel.swift
  LiarGame/Sources/ViewController/RandomMusicQuiz/RandomMusicQuizView.swift
  LiarGame/Sources/ViewController/RandomMusicQuiz/RandomMusicQuizViewController.swift
  LiarGame/Sources/ViewController/SplashViewController.swift
  Project.yml
  scripts/swiftformat.sh
  scripts/swiftlint.sh
  swiftlint.yml
Labels: 🦴 Refactoring 🦴, ⚙️ Project Fix ⚙️

#27 swiftformat sortDeclarations 주석처리
  .swiftformat
Labels: 🐛 Bug 🐛, 🚨 Emergency 🚨

#28 색상 추가
  LiarGame/Sources/Utils/UIColor+Extensions.swift
  LiarGame/Sources/ViewController/HomeViewController.swift
  LiarGame/Sources/ViewController/LiarGame/LiarGameModeViewController.swift
  LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
  LiarGame/Sources/ViewController/LiarGame/LiarGameViewController.swift
  LiarGame/Sources/ViewController/RandomMusicQuiz/RandomMusicQuizView.swift
  LiarGame/Sources/ViewController/SplashViewController.swift
Labels: 🦴 Refactoring 🦴

#25 LiarGame Subject에 따라서 단어 변경 및 Game Model 추가
  LiarGame/Sources/Model/LiarGameModel.swift
  LiarGame/Sources/Reactor/LiarGameReactor.swift
Labels: 🚀 feature 🚀

#26 Liar Game Mode Select Develop
  LiarGame/Sources/Reactor/LiarGameReactor.swift
  LiarGame/Sources/ViewController/LiarGame/LiarGameViewController.swift
Labels: 🚀 feature 🚀

#24 LiarSubjectViewController 소스 리팩토링
  LiarGame/Sources/Model/LiarSubjectModel.swift
  LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
  LiarGame/Sources/ViewController/LiarGame/LiarGameViewController.swift
Labels: 🦴 Refactoring 🦴

#31 fix: Fix LiarGameSubjectVC Naming error
  LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
Labels: 🐛 Bug 🐛, 🚨 Emergency 🚨

#30 reformat random music view controller
  LiarGame/Sources/ViewController/RandomMusicQuiz/RandomMusicQuizViewController.swift
Labels: 🦴 Refactoring 🦴

#32 style: Reformat RandomMusicQuizView
  LiarGame/Sources/ViewController/RandomMusicQuiz/RandomMusicQuizView.swift
Labels: 🦴 Refactoring 🦴

#33 Reformat RandomMusicQuizReactor
  LiarGame/Sources/Model/YoutubePlayerState.swift
  LiarGame/Sources/Reactor/RandomMusicQuizReactor.swift
  LiarGame/Sources/ViewController/RandomMusicQuiz/RandomMusicQuizViewController.swift
Labels: 🦴 Refactoring 🦴

#34 chore: Comment unused swiftformat option
  .swiftformat
  Project.yml
Labels: ⚙️ Project Fix ⚙️

#36 LiarGame 가림막 Animation 추가
  LiarGame/Sources/ViewController/LiarGame/LiarGameViewController.swift
Labels: 🚀 feature 🚀

#37 Change RandomMusicQuizView layout
  LiarGame/Sources/ViewController/RandomMusicQuiz/RandomMusicQuizView.swift
  LiarGame/Sources/ViewController/RandomMusicQuiz/RandomMusicQuizViewController.swift
Labels: 🦴 Refactoring 🦴

#39 feat: Add Animation
  LiarGame/Resources/Assets.xcassets/music_playing.dataset/Contents.json
  LiarGame/Resources/Assets.xcassets/music_playing.dataset/music_playing.json
  LiarGame/Sources/ViewController/RandomMusicQuiz/RandomMusicQuizView.swift
  LiarGame/Sources/ViewController/RandomMusicQuiz/RandomMusicQuizViewController.swift
Labels: 🚀 feature 🚀

#38 게임이 종료되었을 때 화면 처리
  LiarGame/Sources/ViewController/LiarGame/LiarGameViewController.swift
Labels: 🚀 feature 🚀

#40 Add Github Action on PR
  .github/workflows/pr.yml
  scripts/swiftformat.sh
  scripts/swiftlint.sh
Labels: ⚙️ Project Fix ⚙️

#41 style: Typo correction
  .github/workflows/pr.yml
  LiarGame/Sources/Model/YoutubePlayerState.swift
  LiarGame/Sources/Reactor/RandomMusicQuizReactor.swift
  LiarGame/Sources/Repository/RandomMusicRepository.swift
  LiarGame/Sources/ViewController/RandomMusicQuiz/RandomMusicQuizViewController.swift
Labels: 🦴 Refactoring 🦴

#42 Add slack message
  .github/workflows/pr.yml
Labels: ⚙️ Project Fix ⚙️

#43 style: Change color hex to static property
  LiarGame/Sources/ViewController/LiarGame/LiarGameViewController.swift
Labels: 🦴 Refactoring 🦴

#44 Add Pure
  LiarGame/Application/AppDependency.swift
  LiarGame/Application/SceneDelegate.swift
  LiarGame/Sources/Reactor/HomeReactor.swift
  LiarGame/Sources/Reactor/LiarGameModeReactor.swift
  LiarGame/Sources/Reactor/LiarGameReactor.swift
  LiarGame/Sources/Reactor/LiarGameSubjectReactor.swift
  LiarGame/Sources/Reactor/RandomMusicQuizReactor.swift
  LiarGame/Sources/ViewController/HomeViewController.swift
  LiarGame/Sources/ViewController/LiarGame/LiarGameModeViewController.swift
  LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
  LiarGame/Sources/ViewController/LiarGame/LiarGameViewController.swift
  LiarGame/Sources/ViewController/RandomMusicQuiz/RandomMusicQuizViewController.swift
  LiarGame/Sources/ViewController/SplashViewController.swift
  Project.yml
Labels: 🦴 Refactoring 🦴
