Repository 2jae6/LiarGame, pull requests merged in 2022-04, with the labels that each got.

#6 라이어게임 모드 선택 화면 프로토타입
  LiarGame/Sources/Model/LiarGameModeModel.swift
  LiarGame/Sources/Reactor/LiarGameModeReactor.swift
  LiarGame/Sources/Reactor/LiarGameSubjectReactor.swift
  LiarGame/Sources/ViewController/HomeViewController.swift
  LiarGame/Sources/ViewController/LiarGame/LiarGameModeViewController.swift
  LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
Labels: 신규 개발, good first issue

#10 [#8] feat: Add RandomMusicRepository
  .gitignore
  LiarGame/Resources/Info.plist
  LiarGame/Sources/Model/Music.swift
  LiarGame/Sources/Model/MusicSheetDTO.swift
  LiarGame/Sources/Repository/RandomMusicRepository.swift
  LiarGame/Sources/Utils/Userdefaults+PropertyWrapper.swift
  xcconfig/LiarGame-Shared.xcconfig
Labels: 신규 개발

#12 LiarGame Subject Select View & LiarGame View early Setup
  LiarGame/Sources/Model/LiarSubjectModel.swift
  LiarGame/Sources/Reactor/LiarGameSubjectReactor.swift
  LiarGame/Sources/ViewController/HomeViewController.swift
  LiarGame/Sources/ViewController/LiarGame/LiarGameModeViewController.swift
  LiarGame/Sources/ViewController/LiarGame/LiarGameSubjectViewController.swift
  LiarGame/Sources/ViewController/LiarGame/LiarGameViewController.swift
  xcconfig/LiarGame-Shared.xcconfig
Labels: 신규 개발, 2jae6
